project:
  type: website

website:
  title: "BDSI R Training I"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: day1.qmd
        text: "Day 1"
      #- href: day1.qmd
      #  text: Day 2
      #- href: day1.qmd
      #  text: Day 3
      #- href: day1.qmd
      #  text: Day 4
      - help.qmd
  body-footer: | 
    [This website is brought to you by [ANU Biological Data Science Institute](https://bdsi.anu.edu.au/).]{.footer}
  margin-header: |
    ![](/images/ANU_Secondary_Horizontal_GoldBlack.png)
format:
  html:
    css: styles.css
    toc: true
    



