project:
  type: website
  render:
   - "*.qmd"
   - "!slides/*"

website:
  title: "BDSI R Training I"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - day1.qmd
      - day2.qmd
      #- day3.qmd
      #- day4.qmd
      - help.qmd
  body-footer: | 
    [This website is brought to you by the [ANU Biological Data Science Institute](https://bdsi.anu.edu.au/).]{.footer}
  margin-header: |
    ![](/images/ANU_Secondary_Horizontal_GoldBlack.png)
format:
  html:
    css: styles.css
    toc: true
    



